name: Test PR on Linux and macOS

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Pixi
      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.25.0
          cache: false
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
          activate-environment: true
          log-level: vvv

      # Verify Pixi installation
      - name: Verify Pixi version
        run: pixi --version

      # Run pixi install
      - name: Install dependencies
        run: pixi install --locked

      # Run setup
      - name: Run setup
        run: pixi run setup

      # Check Dependencies
      - name: Check dependencies
        run: which emcc emrun brian2wasm emsdk
        shell: pixi run bash -e {0}
